// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkcC2BlGqASNt2F1yANHr3r0PHEITOrnI',
    appId: '1:95444687814:web:56bec21a18d2c24ab930c7',
    messagingSenderId: '95444687814',
    projectId: 'pdmusers-73fec',
    authDomain: 'pdmusers-73fec.firebaseapp.com',
    databaseURL: 'https://pdmusers-73fec-default-rtdb.firebaseio.com',
    storageBucket: 'pdmusers-73fec.appspot.com',
    measurementId: 'G-DZL13SB7R7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVWBEVkQ-9MZfrgDrDKGcw4s5ecZxtcRY',
    appId: '1:95444687814:android:261a11b4c91cf7eeb930c7',
    messagingSenderId: '95444687814',
    projectId: 'pdmusers-73fec',
    databaseURL: 'https://pdmusers-73fec-default-rtdb.firebaseio.com',
    storageBucket: 'pdmusers-73fec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYcUCIDytlIBSBanO3-swr0b7XfwjInb8',
    appId: '1:95444687814:ios:397eefe8ea8dbdf3b930c7',
    messagingSenderId: '95444687814',
    projectId: 'pdmusers-73fec',
    databaseURL: 'https://pdmusers-73fec-default-rtdb.firebaseio.com',
    storageBucket: 'pdmusers-73fec.appspot.com',
    iosClientId:
        '95444687814-og901svosm4dmeqq5q307gv1fvv7i65o.apps.googleusercontent.com',
    iosBundleId: 'com.example.pdmbdHis',
  );
}
